[metadata]
addr = 0x40071d
size = 0xb8

[header]
name = "mahaloz_main"
addr = 0x40071d

[stack_vars.-0x28]
offset = -40
name = "special_var"
type = "mahaloz_struct"
size = 0x10
addr = 0x40071d

[stack_vars.-0x2c]
offset = -44
name = "ret_val"
type = "int"
size = 0x4
addr = 0x40071d

[stack_vars.-0x10]
offset = -16
name = "unusedVar2"
size = 0x1
addr = 0x40071d

[stack_vars.-0x18]
offset = -24
name = "firstString"
size = 0x1
addr = 0x40071d

[stack_vars.-0x3c]
offset = -60
name = "processedInput1"
size = 0x4
addr = 0x40071d

[stack_vars.-0x48]
offset = -72
name = "processedInput2"
size = 0x8
addr = 0x40071d

[stack_vars.-0x20]
offset = -32
name = "unusedVar1"
size = 0x1
addr = 0x40071d
