[0x40071d]
addr = 0x40071d
func_addr = 0x40071d
comment = "***\nThis is a large function comment.\nThanks for using BinSync!\n\n<3 mahaloz\n***\n"
decompiled = false

[0x400739]
addr = 0x400739
func_addr = 0x40071d
comment = "probs some username thing!\n"
decompiled = true
