[mahaloz_enum]
last_change = 2022-12-20T22:02:36.215571Z
name = "mahaloz_enum"

[binsync_enum]
last_change = 2023-11-27T20:09:35.275396Z
name = "binsync_enum"

[mahaloz_enum.members]
mahaloz_enum_0 = 0x0

[binsync_enum.members]
BS_VALID = 0x0
BS_INVALID = 0x1
